version: '3.7'

services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    expose:
      - 5432
    ports:
      - '5432:5432'
    restart: always
    # networks:
    #   - goodlist-network
    # volumes:
    #   # - postgres:/var/lib/postgresql/data
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./dbscripts/database.env

  web:
    build: .
    ports:
      - '5000:5000'
    # goodlist:
    #   image: goodlist:latest
    #   network_mode: bridge
    #   # restart: always
    #   container_name: goodlist
    #   depends_on:
    #     - 'postgres'
    #   build:
    #     context: .
    #     dockerfile: Dockerfile
    #   # expose:
    #   #   - 8080
    #   # ports:
    #   #   - 8080:8080
    #   depends_on:
    #     - postgres
    #   links:
    #     - postgres
    # environment:
    # DB_CONNECTION_STRING: "Server=localhost,5432;Database=goodlist;Password=root;"
    # networks:
    #   - goodlist-network
  # networks:
  #   goodlist-network:
  #     driver: bridge
# volumes:
#   postgres-data:
